[theme]

# Primary accent for interactive elements
primaryColor = "#d33682"

# Background color for the main content area
backgroundColor = "#2C2C2E"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#7D7B7B"

# Color used for almost all text
textColor = "#fafafa"

# Text font style
font="sans serif"
