
name: CD
on:
  release:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        poetry-version: ["1.7.1", "1.8.3"]
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install pkg with poetry
        run: poetry install
      - name: Check for code validity
        run: |
          poetry run black interop --check
          poetry run isort interop -c
          poetry run flake8 interop
      - name: Run tests
        run: poetry run pytest -v interop/tests
      - name: Generate distribution files
        run: poetry build
      - name: Publish Distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
